# Generated by Django 5.2.1 on 2025-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza_lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pizza', models.CharField(max_length=100)),
                ('ingredientes', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pizzas/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
