# Generated by Django 5.2.1 on 2025-06-03 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('pizza_solicitada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pizza_lista')),
            ],
        ),
    ]
