# Generated by Django 5.2.1 on 2025-06-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoria_pizza_remove_pedido_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_pedido'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='pizza',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(max_length=100, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pizza_solicitada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pizza', verbose_name='Pizza'),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Valoracion',
        ),
    ]
